substitutions:
  _SHEET_ID: ''
  _SHEET_NAME: ''
  _SHEET_RANGE: ''
  _SEND_MAIL_URL: ''
  _QUEUE_NAME: ''
  _TASKS_REGION: ''
  _TASKS_SERVICE_ACCOUNT: ''
  _TASKS_AUDIENCE: ''
  _FIREBASE_API_KEY: ''

steps:
  # 依存関係をインストール
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['install']
    dir: 'functions'

  # TypeScriptをビルド
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['run', 'build']
    dir: 'functions'

  # Cloud Functionsへデプロイ
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - functions
      - deploy
      - sheetPuller
      - --gen2
      - --runtime=nodejs20
      - --region=asia-northeast1
      - --source=functions
      - --entry-point=sheetPuller
      - --trigger-http
      - --allow-unauthenticated
      - --set-env-vars=SHEET_ID=$_SHEET_ID,SHEET_NAME=$_SHEET_NAME,SHEET_RANGE=$_SHEET_RANGE,SEND_MAIL_URL=$_SEND_MAIL_URL,QUEUE_NAME=$_QUEUE_NAME,TASKS_REGION=$_TASKS_REGION,TASKS_SERVICE_ACCOUNT=$_TASKS_SERVICE_ACCOUNT

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - functions
      - deploy
      - sendMail
      - --gen2
      - --runtime=nodejs20
      - --region=asia-northeast1
      - --source=functions
      - --entry-point=sendMail
      - --trigger-http
      - --allow-unauthenticated
      - --set-env-vars=TASKS_AUDIENCE=$_TASKS_AUDIENCE,TASKS_SERVICE_ACCOUNT=$_TASKS_SERVICE_ACCOUNT

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - functions
      - deploy
      - login
      - --gen2
      - --runtime=nodejs20
      - --region=asia-northeast1
      - --source=functions
      - --entry-point=login
      - --trigger-http
      - --allow-unauthenticated
      - --set-env-vars=FIREBASE_API_KEY=$_FIREBASE_API_KEY

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - functions
      - deploy
      - getCount
      - --gen2
      - --runtime=nodejs20
      - --region=asia-northeast1
      - --source=functions
      - --entry-point=getCount
      - --trigger-http
      - --allow-unauthenticated

